name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '📝 Content Updates'
    labels:
      - 'content'
  - title: '🎨 Styles'
    labels:
      - 'styles'
  - title: '🔧 Config & Dependencies'
    labels:
      - 'config'
      - 'dependencies'
  - title: '⚙️ GitHub Actions'
    labels:
      - 'github-actions'
  - title: '📚 Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'content'
      - 'styles'
      - 'config'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
