name: Auto Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Apply labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Apply labels based on changed files
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
